### ISSUE TITLE
splines package is not in CRAN anymore

### ISSUE THREAD

**Issue by iagomosqueira** [flr/FLa4a#70]
http://cran.r-project.org/web/packages/splines/index.html

**Comment by colinpmillar** [comment]
Hi Iago,

splined has been shipped with R for a while and does not appear on cran anymore... I think other packages like grid are also not on cran but shipped with R.

Here is the tar.gz for the latest R release:
![screenshot from 2015-03-10 18 59 38](https://cloud.githubusercontent.com/assets/1502848/6582823/d46a2dc0-c757-11e4-9f85-af22f92a783f.png)

**Comment by iagomosqueira** [comment]
Yes, sorry. What is being used from splines?

Iago

---
Sent from Android
O Mar 10, 2015 8:02 PM, "Colin Millar" <notifications@github.com> escribiu:

**Comment by colinpmillar** [comment]
Nothing really, it should just be a suggests or enhances or something. We
do use mgcv, but splines is just a optional extra

**Comment by iagomosqueira** [comment]
So if no function it is being used or overloaded, would it be better to
drop its import?

Iago

---
Sent from Android
O Mar 10, 2015 11:02 PM, "Colin Millar" <notifications@github.com> escribiu:

> Nothing really, it should just be a suggests or enhances or something. We
> do use mgcv, but splines is just a optional extra

**Comment by ejardim** [comment]
Updated git with a fix for getX just now.

EJ
