### ISSUE TITLE
In the qmodel when specifying +year, is the resultant trend actually linear?

### ISSUE THREAD

**Issue by jaado** [flr/FLa4a#75]
The example appears as Figure 33 in the a4a technical document. The associated qmodel is:
qmod <- list(~s(age,k=4) + year)
In Figure 33, the trend across time for the youngest age appears to be non-linear (the line curves). Is this a plotting issue, are an issue with the calculation?

**Comment by ejardim** [comment]
Nope, should be linear in the log scale ... need to fix the documentation.
